### ISSUE TITLE
Normalize OpenAlex types of works

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/works-finder#1]
Map everything to barometre type
(use an aggregate on bso-publications + bso-datacite indices to gel all possibles values)
e.g article from OpenAlex ==> journal-article

**Comment by annelhote** [comment]
Here are the French Monitor type:
- journal-article
- book-chapter
- proceedings
- book
- preprint

**Comment by annelhote** [comment]
Here are the OpenAlex works types (order by frequency) :
- article
- book-chapter
- dissertation
- book
- dataset
- paratext
- reference-entry
- other
- report
- peer-review
- standard
- editorial
- erratum
- journal-article
- letter
- grant
- book-part
- journal-volume
- proceedings-article
- book-series
- posted-content
- proceedings-series
- book-set
- monograph
- journal-issue
- component
- proceedings
- journal
- reference-book
- report-series

**Comment by ericjeangirard** [comment]
i would say posted-content -> preprint( not 100% sure)
some doubt also about dissertations, but other is ok for now i guess

**Comment by annelhote** [comment]
1. "posted-content" is now "preprint" even if this type did not exist in the French OSM.
2. Should we normalize the French OSM types of works ?
Otherwise it is implemented, and the search in works view too
