### ISSUE TITLE
Option to display only matching affiliations

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/works-finder#4]
In the Affiliations tab, option to display only the affiliations that do match one of the criteria, rather than all the affiliations encountered.
(checked by default ?)
And maybe, in the affiliation view, add a column with the number of matching expressions
(ex: if the query is "ecole polytechnique" + "palaiseau" => "ecole polytechnique, route de saclay, palaiseau" has 2 matches

**Comment by annelhote** [comment]
It should be deployed on Github Pages now.
But maybe the "Number of matches" column is not really meaningful. Should we add something like "1 / 2" where 2 is the number of affiliations searched ?

**Comment by ericjeangirard** [comment]
Yes i guess we should help the user to understand what it means.
Some ideas:
- bold font for matching text
- add some explaining text: "All the affiliations of the publications found in OpenAlex and French OSM are listed below. A filter can be applied to view only the affiliations containing at least one of the matching query input (this filter is applied by default but can be removed)" ?
- sortable column (number of works and number of matches) ?

**Comment by ericjeangirard** [comment]
With https://dataesr.github.io/works-finder/#/?affiliations=ecole+polytechnique&dataIdentifiers=crossref&dataIdentifiers=hal_id&dataIdentifiers=datacite&datasources=bso&datasources=openalex&endYear=2021&moreOptions=false&startYear=2021 
I don't see matching text in bold ?

**Comment by annelhote** [comment]
bug because of the two words affiliation search.

**Comment by annelhote** [comment]
Would you please test again in order to find new bugs ?

**Comment by ericjeangirard** [comment]
;-)
Avec https://dataesr.github.io/works-finder/#/?affiliations=ecole+polytechnique&affiliations=05hy3tk52&dataIdentifiers=crossref&dataIdentifiers=hal_id&dataIdentifiers=datacite&datasources=bso&datasources=openalex&endYear=2021&moreOptions=false&startYear=2021

**École polytechnique**, X, **École polytechnique**, 91128 Palaiseau Cedex, France ==> should be 1 match (not 2) as only one input matches
**École Polytechnique** **05hy3tk52** ==> should be 2 matches (not 1)

**Comment by ericjeangirard** [comment]
+ https://dataesr.github.io/works-finder/#/?affiliations=05hy3tk52&dataIdentifiers=crossref&dataIdentifiers=hal_id&dataIdentifiers=datacite&datasources=bso&datasources=openalex&endYear=2021&moreOptions=false&startYear=2021 ==> the affiliation view is broken

**Comment by ericjeangirard** [comment]
Also, then the "Filter on matching affiliations" is unselected, the waiting time is very long
(example with https://dataesr.github.io/works-finder/#/?affiliations=mines+de+paris&dataIdentifiers=crossref&dataIdentifiers=hal_id&dataIdentifiers=datacite&datasources=bso&datasources=openalex&endYear=2021&moreOptions=false&startYear=2021)

**Comment by annelhote** [comment]
And search in affiliation name is now restored
