### ISSUE TITLE
In the Affiliations tab, display RoR id in the affiliations name column

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/works-finder#5]
If a RoR is associated to an affiliation also use it in the normalized version of the affiliation, and in the displayed name.

In both BSO and OpenAlex, the RoR is (sometimes) given within the affiliation object.

**Comment by annelhote** [comment]
@ericjeangirard 
1. Should it be done on the works tab too ?
2. For the French Monitor works, the RoR is displayed if present. For the OpenAlex works, the match is doable (and done) only if there is only one affiliation.

**Comment by ericjeangirard** [comment]
> 1. Should it be done on the works tab too ?

yes (i guess ?)

> 2. For the French Monitor works, the RoR is displayed if present. For the OpenAlex works, the match is doable (and done) only if there is only one affiliation.

ok!

**Comment by annelhote** [comment]
It should be OK. I'll let you close the issue if it's OK for you.
